name: deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  createFile:
    name: Create a file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 1arp/create-a-file-action@0.4.5
        with:
          path: 'SeniorProject/src/main/resources'
          isAbsolutePath: false
          file: 'application.properties'
  build:
    needs: createFile
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Inject secrets into application.properties
        run: |
          echo "spring.jpa.hibernate.ddl-auto=update" >> SeniorProject/src/main/resources/application.properties
          echo "spring.datasource.url=${{ secrets.DB_URL }}" >> SeniorProject/src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> SeniorProject/src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> SeniorProject/src/main/resources/application.properties
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> SeniorProject/src/main/resources/application.properties
          echo "sspring.jpa.show-sql: true" >> SeniorProject/src/main/resources/application.properties
          echo "security.jwt.secret-key=${{ secrets.JWT_KEY }}" >> SeniorProject/src/main/resources/application.properties
          echo "security.jwt.expiration-time=${{ secrets.JWT_EXPIRATION_TIME }}" >> SeniorProject/src/main/resources/application.properties
          echo "server.port=5000" >> SeniorProject/src/main/resources/application.properties
          cat SeniorProject/src/main/resources/application.properties
      - name: Navigate to app folder, clean and package Maven build
        run: |
          cd SeniorProject
          mvn clean install
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/SeniorProject-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          application_name: weddingRental-test
          environment_name: WeddingRental-test-env
          version_label: ${{ github.sha }}
          region: us-west-1
          deployment_package: SeniorProject-0.0.1-SNAPSHOT.jar
